# Generated by Django 4.2.3 on 2024-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paymentadmissionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesEntryAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues_auto_student_id', models.CharField(max_length=14)),
                ('dues_auto_year', models.CharField(max_length=5)),
                ('dues_auto_season', models.CharField(max_length=10)),
                ('dues_auto_program', models.CharField(max_length=150)),
                ('dues_auto_discount', models.CharField(blank=True, max_length=20)),
                ('dues_auto_date', models.CharField(max_length=20)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
