# Generated by Django 4.2.3 on 2024-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_duesentryauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntryAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_auto_student_id', models.CharField(max_length=14)),
                ('p_auto_amount', models.CharField(max_length=20)),
                ('p_auto_money_receipt', models.CharField(max_length=25)),
                ('p_auto_campus', models.CharField(max_length=20)),
                ('p_auto_mode_payment', models.CharField(max_length=20)),
                ('p_auto_date', models.CharField(max_length=20)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
